# Generated by Django 5.2 on 2025-06-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_role',
            field=models.CharField(choices=[('passenger', 'Passenger'), ('vehicle_owner', 'Vehicle Owner'), ('sacco_admin', 'Sacco Admin')], default='passenger', max_length=20),
        ),
    ]
