# Generated by Django 5.2 on 2025-05-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0002_sacco_sacco_admin_saccoadminrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sacco',
            name='date_established',
            field=models.DateField(blank=True, help_text='The date the SACCO was established', null=True),
        ),
    ]
