# Generated by Django 5.2 on 2025-06-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0003_alter_sacco_date_established'),
    ]

    operations = [
        migrations.AddField(
            model_name='saccoadminrequest',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='saccoadminrequest',
            name='date_established',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saccoadminrequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='saccoadminrequest',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='saccoadminrequest',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
