# Generated by Django 5.2 on 2025-06-09 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0005_sacco_admin_requests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sacco',
            name='admin_requests',
        ),
    ]
