# Generated by Django 5.2 on 2025-06-28 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0006_remove_sacco_admin_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='sacco',
            name='avg_daily_trips_per_vehicle',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sacco',
            name='avg_vehicle_monthly_earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sacco',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='sacco',
            name='daily_target',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='sacco',
            name='weekly_bonus_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='sacco',
            name='weekly_bonus_threshold',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.CreateModel(
            name='SaccoFinancialMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_monthly_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('avg_revenue_per_vehicle', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('revenue_growth_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('operational_costs', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('maintenance_costs', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('insurance_costs', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('licensing_costs', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_profit_margin', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('owner_average_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('sacco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sacco.sacco')),
            ],
        ),
    ]
