# Generated by Django 5.2 on 2025-06-28 14:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0008_alter_sacco_avg_daily_trips_per_vehicle_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saccofinancialmetrics',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='saccofinancialmetrics',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
