# Generated by Django 5.2 on 2025-06-23 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routes', '0001_initial'),
        ('sacco', '0006_remove_sacco_admin_requests'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('vehicle_type', models.CharField(choices=[('matatu', 'Matatu'), ('bus', 'Bus'), ('minibus', 'Minibus'), ('van', 'Van')], max_length=20)),
                ('seating_capacity', models.PositiveIntegerField()),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid'), ('electric', 'Electric')], max_length=20)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monthly_insurance', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('monthly_maintenance', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('fuel_consumption_per_km', models.DecimalField(decimal_places=2, help_text='Liters per KM', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('is_approved_by_sacco', models.BooleanField(default=False)),
                ('date_joined_sacco', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
                ('sacco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='sacco.sacco')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('passengers_count', models.PositiveIntegerField()),
                ('fare_collected', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fuel_consumed', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.route')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-date', '-departure_time'],
            },
        ),
        migrations.CreateModel(
            name='SaccoJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_years', models.PositiveIntegerField(help_text='Years of PSV experience')),
                ('reason_for_joining', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('under_review', 'Under Review')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Notes from sacco admin')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('preferred_routes', models.ManyToManyField(blank=True, help_text='Routes owner is interested in', to='routes.route')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_join_requests', to=settings.AUTH_USER_MODEL)),
                ('sacco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='sacco.sacco')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-requested_at'],
                'unique_together': {('vehicle', 'sacco')},
            },
        ),
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('logbook', 'Logbook'), ('insurance', 'Insurance Certificate'), ('inspection', 'Inspection Certificate'), ('license', 'Driving License'), ('permit', 'PSV License/Permit'), ('ntsa', 'NTSA Certificate'), ('other', 'Other')], max_length=20)),
                ('document_name', models.CharField(max_length=100)),
                ('document_file', models.FileField(upload_to='vehicle_documents/')),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vehicles.vehicle')),
            ],
            options={
                'unique_together': {('vehicle', 'document_type')},
            },
        ),
        migrations.CreateModel(
            name='VehiclePerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('total_trips', models.PositiveIntegerField(default=0)),
                ('total_distance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_passengers', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fuel_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('maintenance_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('sacco_commission', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('average_occupancy', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fuel_efficiency', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_records', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-month'],
                'unique_together': {('vehicle', 'month')},
            },
        ),
    ]
