# Generated by Django 5.2 on 2025-06-27 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sacco', '0006_remove_sacco_admin_requests'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaccoAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sacco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='sacco.sacco')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sacco_admin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sacco Admin',
                'verbose_name_plural': 'Sacco Admins',
                'unique_together': {('user', 'sacco')},
            },
        ),
    ]
